// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Preventyon.Data;

#nullable disable

namespace Preventyon.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20240715102313_table4")]
    partial class table4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Preventyon.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RoleId")
                        .HasMaxLength(100)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Preventyon.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("actionAssignedTo")
                        .HasColumnType("text");

                    b.Property<string>("associatedImpacts")
                        .HasColumnType("text");

                    b.Property<string>("category")
                        .HasColumnType("text");

                    b.Property<string>("collectionOfEvidence")
                        .HasColumnType("text");

                    b.Property<string>("correction")
                        .HasColumnType("text");

                    b.Property<DateTime>("correctionActualCompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("correctionCompletionTargetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("correctionDetailsTimeTakenToCloseIncident")
                        .HasColumnType("numeric");

                    b.Property<string>("correctiveAction")
                        .HasColumnType("text");

                    b.Property<DateTime>("correctiveActualCompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("correctiveDetailsTimeTakenToCloseIncident")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deptOfAssignee")
                        .HasColumnType("text");

                    b.Property<string>("incidentDescription")
                        .HasColumnType("text");

                    b.Property<string>("incidentNo")
                        .HasColumnType("text");

                    b.Property<DateTime>("incidentOccuredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("incidentStatus")
                        .HasColumnType("text");

                    b.Property<string>("incidentTitle")
                        .HasColumnType("text");

                    b.Property<string>("incidentType")
                        .HasColumnType("text");

                    b.Property<string>("investigationDetails")
                        .HasColumnType("text");

                    b.Property<bool>("isDraft")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("monthYear")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("priority")
                        .HasColumnType("text");

                    b.Property<string>("reportedBy")
                        .HasColumnType("text");

                    b.Property<string>("roleOfReporter")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Incident");
                });

            modelBuilder.Entity("Preventyon.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("incidentCreateOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("incidentManagement")
                        .HasColumnType("boolean");

                    b.Property<string>("permissionName")
                        .HasColumnType("text");

                    b.Property<bool>("userManagement")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("Preventyon.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("permissionID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("permissionID")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Preventyon.Models.Employee", b =>
                {
                    b.HasOne("Preventyon.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Preventyon.Models.Incident", b =>
                {
                    b.HasOne("Preventyon.Models.Employee", null)
                        .WithMany("Incidents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Preventyon.Models.Role", b =>
                {
                    b.HasOne("Preventyon.Models.Permission", "permission")
                        .WithOne("Role")
                        .HasForeignKey("Preventyon.Models.Role", "permissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("permission");
                });

            modelBuilder.Entity("Preventyon.Models.Employee", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Preventyon.Models.Permission", b =>
                {
                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
